name: Publish Firefox Add-on
description: Upload and publish add-on to Firefox Addons
author: Hyperbola

inputs:
  guid:
    description: Add-on GUID.
    required: true
  xpi-path:
    description: Path to the add-on .zip file.
    required: true
  tester-only:
    description: If true then the add-on is published to listed users only. Default to false.
    required: false
    default: "false"
  jwt-issuer:
    description: Firefox Addons JWT issuer.
    required: true
  jwt-secret:
    description: Firefox Addons JWT secret.
    required: true

runs:
  using: node16
  main: "index.js"

branding:
  icon: aperture
  color: blue
